name: codacy-coverage-reporter

on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
