name: Format JS (ESLint Fix)

on:
  push:
    branches:
      - "master"
      paths:
        - '**.ts'
        - '**.js'
  pull_request:
    paths:
        - '**.ts'
        - '**.js'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: NPM Install
        run: |
          npm install --no-save eslint eslint-config-google typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin  


      - name: Run ESLint and fix what can be fixed
        run: 
          npx eslint --fix . || exit 0
          

      - name: Determine Changes and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply eslint fixes
          commit_user_name: brainvation Bot
          commit_user_email: "apps@brainvation.de"
