name: Fix JS errors (ESLint Fix)

on:
  push:
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.php"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: NPM Install
        run: |
          npm install --no-save eslint eslint-config-google typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin  


      - name: Run ESLint and Fix what can be fixed
        run: 
          npx eslint --fix . || exit 0
          

      - name: Determine Changes and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          commit_user_name: brainvation Bot
          commit_user_email: "apps@brainvation.de"
          file_pattern: "!package-lock.json !package.json"
