name: Format PHP (PHP CS Fixer)

on:
  push:
    branches:
      - "master"
    paths:
      - "**.php"
  pull_request:
    paths:
      - "**.php"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: composer install

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix

      - name: Determine Changes and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
          commit_user_name: brainvation Bot
          commit_user_email: "apps@brainvation.de"
          file_pattern: "*.php"
