name: Format code (prettier)

on:
  push:
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.php"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: NPM Install
        run: npm install prettier --no-save

      - name: Run prettier
        run: npx prettier --write .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          commit_user_name: brainvation Bot
          commit_user_email: apps@brainvation.de
          file_pattern: !package-lock.json !package.json
